"""add pipelinerunlog

Revision ID: b508f7f1a302
Revises: c84f95aa1b65
Create Date: 2024-07-31 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b508f7f1a302'
down_revision = 'c84f95aa1b65'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('alerts_generated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_run_logs_run_timestamp'), 'pipeline_run_logs', ['run_timestamp'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_run_logs_run_timestamp'), table_name='pipeline_run_logs')
    op.drop_table('pipeline_run_logs')
    # ### end Alembic commands ###
